name: CI

on: [push]

jobs:
  Run-All-Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v6
        with:
          version: 2
          php_version: 8.1
          args: --ignore-platform-reqs --optimize-autoloader --classmap-authoritative

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          configuration: ./phpunit.xml
          bootstrap: ./vendor/autoload.php
          version: 9.5
          php_version: 8.1
