name: CI

on: [push]

jobs:
  Run-All-Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml
          args: --coverage-text
          version: 9.5
          php_version: 8.1
