name: Run all tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-verson: 8.1
    - name: Check files
      run: ls -la vendor
    - name: Run all tests
      run: composer install && ./vendor/bin/phpunit
